#pragma once
#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900

#define SCREEN_WIDTH_MAX 1600
#define SCREEN_WIDTH_MIN -1600
#define SCREEN_HEIGHT_MAX 900
#define SCREEN_HEIGHT_MIN -900
#define SCREEN_DEPTH_MAX 1600
#define SCREEN_DEPTH_MIN -1600

#define PI 3.141592

#define DISTANCE_FROM_SUN_TO_MERCURY 100
#define DISTANCE_FROM_MERCURY_TO_VENUS 50
#define DISTANCE_FROM_VENUS_TO_EARTH 50
#define DISTANCE_FROM_EARTH_TO_MARS 50
#define DISTANCE_FROM_MARS_TO_JUPITER 200
#define DISTANCE_FROM_JUPITER_TO_SATURN 150
#define DISTANCE_FROM_SATURN_TO_URANUS 100
#define DISTANCE_FROM_URANUS_TO_NEPTUNE 100

#define STAR_ROTATION_HOUR_PER_mSECOND 1
#define STAR_REVOLUTION_DAY_PER_mSECOND 24